/**
 * profile-and-analyze.ts — Profiling + analysis harness for God-AI tuning.
 *
 * Combines profile-godai.ts (profiling) and analyze-profile.ts (analysis) into
 * a single workflow:
 *   1. Run profiling (headless games via runSimulation) to generate a .cpuprofile
 *   2. Automatically analyze the generated profile for self-time hot spots
 *
 * Usage:
 *   bun tools/perf/profile-and-analyze.ts
 *       # Default: run profile then analyze
 *
 *   bun tools/perf/profile-and-analyze.ts --games=50 --diff=chaos --stage=0
 *       # Profile with custom params, then analyze
 *
 *   bun tools/perf/profile-and-analyze.ts --analyze-only /tmp/sim-godai.cpuprofile
 *       # Skip profiling, only analyze an existing cpuprofile
 *
 *   bun tools/perf/profile-and-analyze.ts --topN=50
 *       # Show top 50 hot spots instead of default 30
 *
 * Profiling requires running with bun's CPU profiler:
 *   bun --cpu-prof --cpu-prof-name=tools/perf/results/profile.cpuprofile tools/perf/profile-and-analyze.ts
 */
import { runSimulation } from '../sim/simulation-runner'
import { STAGES } from '../../src/config/stages'
import { DEFAULT_GOD_AI_PARAMS } from '../../src/ai/GodAIInput'
import { readFileSync } from 'node:fs'

// ---------------------------------------------------------------------------
// CLI argument parsing
// ---------------------------------------------------------------------------
function argStr(name: string, fallback: string): string {
  const m = process.argv.find((a) => a.startsWith(`--${name}=`))
  return m ? m.split('=')[1] : fallback
}

function argNum(name: string, fallback: number): number {
  const m = process.argv.find((a) => a.startsWith(`--${name}=`))
  return m ? Number(m.split('=')[1]) : fallback
}

const ANALYZE_ONLY = argStr('analyze-only', '')
const GAMES = argNum('games', 30)
const DIFF = argStr('diff', 'chaos')
const STAGE_IDX = argNum('stage', 0)
const WARMUP = argNum('warmup', 3)
const TOP_N = argNum('topN', 30)
const OUTPUT_PATH = argStr('output', 'tools/perf/results/profile.cpuprofile')

// ---------------------------------------------------------------------------
// Profiling logic (from profile-godai.ts)
// ---------------------------------------------------------------------------
function runProfiling(): string {
  const stage = STAGES[STAGE_IDX]
  if (!stage) {
    console.error(`No stage at index ${STAGE_IDX}`)
    process.exit(1)
  }

  console.log(
    `=== Profiling: ${GAMES} games, diff=${DIFF}, stage=${STAGE_IDX}, warmup=${WARMUP} ===`,
  )

  // Warmup: run a few games first (separate seed range) so the JIT is hot and
  // the timed loop measures steady-state cost, not cold-start. Warmup games use
  // a distinct negative seed range so the TIMED seeds (1000+g*7) stay identical
  // run-to-run — keeping the determinism signature comparable across measures.
  for (let g = 0; g < WARMUP; g++) {
    runSimulation({
      seed: -1000 - g * 7,
      stage,
      difficulty: DIFF,
      godAIParams: DEFAULT_GOD_AI_PARAMS,
      maxTicks: 36000,
      sampleInterval: 100000,
    })
  }

  const t0 = performance.now()
  let totalTicks = 0
  let wins = 0
  let gameovers = 0
  let timeouts = 0
  for (let g = 0; g < GAMES; g++) {
    const res = runSimulation({
      seed: 1000 + g * 7,
      stage,
      difficulty: DIFF,
      godAIParams: DEFAULT_GOD_AI_PARAMS,
      maxTicks: 36000,
      sampleInterval: 100000, // disable per-frame metric sampling to isolate sim core
    })
    totalTicks += res.ticks
    if (res.outcome === 'stage_clear') wins++
    else if (res.outcome === 'gameover') gameovers++
    else timeouts++
  }
  const wall = performance.now() - t0
  const msPerTick = wall / totalTicks
  console.log(
    `games=${GAMES} diff=${DIFF} stage=${STAGE_IDX} | ticks=${totalTicks} wall=${wall.toFixed(0)}ms ` +
      `(${(wall / GAMES).toFixed(1)}ms/game) | perTick=${msPerTick.toFixed(3)}ms ` +
      `| win=${wins} go=${gameovers} timeout=${timeouts}`,
  )

  // Note: The actual cpuprofile is generated by bun --cpu-prof flag.
  // This script just runs the workload. The user must invoke with:
  //   bun --cpu-prof --cpu-prof-name=<OUTPUT_PATH> tools/perf/profile-and-analyze.ts
  console.log(`\nNote: To generate a cpuprofile, run with:`)
  console.log(`  bun --cpu-prof --cpu-prof-name=${OUTPUT_PATH} tools/perf/profile-and-analyze.ts`)

  return OUTPUT_PATH
}

// ---------------------------------------------------------------------------
// Analysis logic (from analyze-profile.ts)
// ---------------------------------------------------------------------------
function analyzeProfile(file: string): void {
  console.log(`\n=== Analyzing: ${file} ===\n`)

  let prof: any
  try {
    prof = JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    console.error(`Failed to read cpuprofile: ${file}`)
    console.error(`Make sure the file exists and was generated by bun --cpu-prof`)
    process.exit(1)
  }

  const nodes: any[] = prof.nodes
  const samples: number[] = prof.samples
  const timeDeltas: number[] = prof.timeDeltas

  const byId = new Map<number, any>()
  for (const n of nodes) byId.set(n.id, n)

  // Bun stores timeDeltas in microseconds.
  const selfMs = new Map<number, number>()
  let totalMs = 0
  for (let i = 0; i < samples.length; i++) {
    const ms = timeDeltas[i] / 1000
    totalMs += ms
    const id = samples[i]
    selfMs.set(id, (selfMs.get(id) ?? 0) + ms)
  }

  function shortUrl(u: string): string {
    const m = u.match(/src\/(.+)$/) || u.match(/tools\/(.+)$/) || u.match(/battle\/(.+)$/)
    return m ? m[1] : u
  }

  // Aggregate by `function @ module` (line stripped). Stripping the line keeps
  // a single function together even if the sampler reports it at multiple
  // inlined positions — giving an unambiguous hot list.
  const agg = new Map<string, { ms: number; file: string; fn: string }>()
  for (const [id, ms] of selfMs) {
    const n = byId.get(id)
    if (!n) continue
    const cf = n.callFrame
    const fn = cf.functionName || '(anonymous)'
    const su = shortUrl(cf.url || '')
    const key = `${fn} @ ${su}`
    const cur = agg.get(key) ?? { ms: 0, file: su, fn }
    cur.ms += ms
    agg.set(key, cur)
  }

  const sorted = [...agg.values()].sort((a, b) => b.ms - a.ms)

  console.log(`total sampled: ${totalMs.toFixed(0)}ms  samples: ${samples.length}\n`)
  console.log(`=== TOP ${TOP_N} BY SELF-TIME (function @ module) ===`)
  let cum = 0
  for (const r of sorted.slice(0, TOP_N)) {
    const pct = (r.ms / totalMs) * 100
    cum += pct
    console.log(
      `${r.ms.toFixed(1).padStart(9)}ms  ${pct.toFixed(1).padStart(5)}%  ${cum
        .toFixed(1)
        .padStart(5)}%  ${r.fn}  @ ${r.file}`,
    )
  }

  // Module-level aggregate.
  const modMs = new Map<string, number>()
  for (const r of sorted) modMs.set(r.file, (modMs.get(r.file) ?? 0) + r.ms)
  console.log(`\n=== BY MODULE (self-time) ===`)
  for (const [f, ms] of [...modMs.entries()].sort((a, b) => b[1] - a[1])) {
    console.log(
      `${ms.toFixed(1).padStart(9)}ms  ${((ms / totalMs) * 100).toFixed(1).padStart(5)}%  ${f}`,
    )
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
if (ANALYZE_ONLY) {
  // Analyze-only mode: skip profiling, just analyze the given file
  analyzeProfile(ANALYZE_ONLY)
} else {
  // Default mode: run profiling then analyze
  const profilePath = runProfiling()

  // Check if the profile file exists before analyzing
  try {
    readFileSync(profilePath, 'utf8')
    analyzeProfile(profilePath)
  } catch {
    console.log(`\nProfile file not found at ${profilePath}`)
    console.log(`To generate and analyze in one step, run:`)
    console.log(`  bun --cpu-prof --cpu-prof-name=${profilePath} tools/perf/profile-and-analyze.ts`)
    console.log(`\nOr analyze an existing profile later with:`)
    console.log(`  bun tools/perf/profile-and-analyze.ts --analyze-only=<file.cpuprofile>`)
  }
}
