#!/usr/bin/env python3
"""weights_prune.py — Weight-file retention manager for nn-training.

Keeps the latest K files per "family" (prefix group); deletes the rest.
Regenerates weights/WEIGHTS.md inventory on demand.

Pure stdlib so it can run in CI before torch is installed.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from datetime import datetime
from pathlib import Path

DEFAULT_KEEP = 3
META_SUFFIX = ".meta.json"
WEIGHTS_MD = "WEIGHTS.md"


def _family_of(rel: str) -> str:
    """Infer family key from a relative filename.

    Examples:
        rl-weights.it1.20260901-120117.json -> rl-weights
        rl-weights.20260824-001921_post-it1ppo.json -> rl-weights
        intent-rl-weights.it1.20260829-160255.json -> intent-rl-weights
        goal-bc/weights.json -> goal-bc/weights
        weights.json -> weights
    """
    stem = rel
    if stem.endswith(META_SUFFIX):
        stem = stem[: -len(META_SUFFIX)]
    if stem.endswith(".json"):
        stem = stem[: -len(".json")]

    m = re.match(r"^(.+?)(?:\.it\d+(?:\.\d{6}-\d{6})?|_post-it\d+ppo)$", stem)
    if m:
        return m.group(1)
    return stem


def _iter_weight_files(root: Path) -> list[tuple[Path, str, float]]:
    """Yield (abs_path, rel_str, mtime) for every .json weight excluding its meta."""
    out: list[tuple[Path, str, float]] = []
    for p in root.rglob("*.json"):
        if p.name.endswith(META_SUFFIX):
            continue
        rel = p.relative_to(root).as_posix()
        out.append((p, rel, p.stat().st_mtime))
    return out


def _sha12(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()[:12]


def _human_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.0f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


def _parse_iter(rel: str) -> str:
    m = re.search(r"\.it(\d+)(?:\.|_post)", rel)
    return m.group(1) if m else "-"


def plan(root: Path, keep: int, apply: bool) -> int:
    files = _iter_weight_files(root)
    by_family: dict[str, list[tuple[Path, str, float]]] = {}
    for item in files:
        fam = _family_of(item[1])
        by_family.setdefault(fam, []).append(item)

    total_keep = 0
    total_delete = 0
    for fam, items in sorted(by_family.items()):
        items.sort(key=lambda x: x[2], reverse=True)
        keepers = items[:keep]
        victims = items[keep:]
        total_keep += len(keepers)
        total_delete += len(victims)
        print(f"[weights-prune] family={fam}: {len(items)} files, "
              f"keep {len(keepers)}, delete {len(victims)}")
        for it in keepers:
            print(f"   KEEP   {it[1]}")
        for it in victims:
            print(f"   DELETE {it[1]}")
            if apply:
                it[0].unlink()
                meta = it[0].with_name(it[0].name + META_SUFFIX)
                if meta.exists():
                    meta.unlink()
                    print(f"           (removed sibling {meta.name})")

    if apply:
        print(f"[weights-prune] deleted {total_delete} files; {total_keep} kept.")
    else:
        print(f"[weights-prune] (dry-run) would delete {total_delete} files "
              f"keeping {total_keep}. Re-run with --apply to confirm.")
    return total_delete


def update_md(root: Path) -> int:
    files = _iter_weight_files(root)
    if not files:
        print(f"[weights-prune] no weight files in {root}")
        return 0
    files.sort(key=lambda x: x[2], reverse=True)

    lines: list[str] = [
        "# weights/WEIGHTS.md",
        "",
        f"_Auto-generated by `weights_prune.py --update-md` "
        f"at {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}.\n",
        f"Total files: **{len(files)}**. "
        f"Prune target: latest **{DEFAULT_KEEP}** per family (`--keep N` to tune).",
        "",
        "| file | sha12 | size | mtime (UTC) | iter |",
        "|------|-------|------|-------------|------|",
    ]
    for p, rel, mtime in files:
        sha = _sha12(p)
        size = _human_size(p.stat().st_size)
        ts = datetime.utcfromtimestamp(mtime).strftime("%Y-%m-%d %H:%M")
        it = _parse_iter(rel)
        lines.append(f"| `{rel}` | `{sha}` | {size} | {ts} | {it} |")

    md_path = root / WEIGHTS_MD
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[weights-prune] updated {md_path} ({len(files)} files inventoried).")
    return len(files)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--keep", type=int, default=DEFAULT_KEEP,
                    help=f"latest K files to retain per family (default {DEFAULT_KEEP})")
    ap.add_argument("--dir", default="weights", help="weights directory")
    ap.add_argument("--apply", action="store_true", help="actually delete (default dry-run)")
    ap.add_argument("--update-md", action="store_true",
                    help="regenerate weights/WEIGHTS.md and exit")
    args = ap.parse_args()

    root = Path(args.dir)
    if not root.is_dir():
        print(f"[weights-prune] ERROR: {root} is not a directory", file=sys.stderr)
        sys.exit(2)

    if args.update_md:
        update_md(root)
        return
    plan(root, args.keep, args.apply)


if __name__ == "__main__":
    main()
