"""remote/hub/queue_peer.py — 七个域混入的**共同对端声明面**（S4 第十五刀）。

## 为什么需要它

`_HubQueue` 拆成七个混入之后，每一簇都要调别的簇的方法（`claim_next` → `discover` /
`_serves_course` / `mode_of` / `active_worker_count` / `_announce_freeze`；`queue_state` →
`halt_of` / `mode_of` / `active_courses` / `offline_courses` / `all_halted` / `active_worker_count`
…）。跨域调用**一律经 `self`**（这是「一个对象、一把锁」能成立的前提，也是零 seam 的来源），
所以每个混入里那些名字都必须有个**来源**。

三种写法里选了第三种：

1. **`Any` 注解** —— mypy 看不见返回类型 ⇒ `return self.all_halted()` 会直接报
   `no-any-return`，而用 `# type: ignore` 消音在本仓是禁的（`warn_unused_ignores=false` 只是
   让 ignore 不留痕，不是许可）；
2. **每个混入各抄一份 `Callable[[...], Ret]`** —— 签名会漂（默认值、关键字-only 表达不了），
   而且同一件事写七遍（正是本仓记过的「同一件事写多遍 = 漂移」）；
3. **本模块一份 `Protocol`** —— 方法签名从原 `_HubQueue` 逐条生成（对账脚本逐字节比过）；
   七个混入写 `class XMixin(QueuePeer)`，mypy 拿到的就是**真签名**（含默认值），而运行时
   **零影响**：Protocol 成员只是声明，MRO 解析到的永远是混入里的真实现。

## 状态**不在**这里

Protocol 里声明的**属性**会在继承它的具体类上变成 abstract 属性
（mypy 实测：`Cannot instantiate abstract class ... with abstract attribute "_solo"`），
而七个混入是要被组合类实例化的。所以状态仍是各混入自己的**裸注解**（
`_stores: dict[str, _JobStore]` 之类，无值）——组合类 `queue.py` 的 `__init__` 是这些字段
**唯一**的带值声明点。

## 为什么 `_store_of` **不在**这里

七个声明里只有 `_store_of` 的签名要 `_JobStore` 这个名字。若把它也放进来，本模块就得
import `remote.hub.store`（L2）⇒ 本模块升到 **L3** ⇒ 七个混入各自 ≥**L4** ⇒ `hub.queue`
**L5** ⇒ `hub_server` **L6** —— 而 `remote/smoke_loopback.py` 是 **L6** 且它 import
`hub_server`，同层就不再「严格向下」（`tests/test_remote_dag.py` 会当场报）。

所以 `_store_of` 由**调用它的那几簇自己声明**（`Callable[[str], "_JobStore | None"]`，签名与
真实现一致）；它们本来就 import `remote.hub.store`（`_stores` 的注解要它），不额外付代价。

## 层号

`queue_peer → {common.protocol, remote.hub.store_leases}`（`ClaimOutcome`）⇒ **L1**。
七个混入站在它 + `hub.store`（L2）上 ⇒ L3；`hub.queue` 组合类 L4，`hub_server` L5。
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from common.protocol import (
    CLAIM_MODE_EXCLUSIVE,
    CLAIM_TTL_SEC,
    COURSE_MODE_ONLINE,
    PEEK_MAX,
    ROLE_ONLINE,
)
from remote.hub.store_leases import ClaimOutcome


class QueuePeer(Protocol):
    """七个域混入互为**对端**：这里只声明「别的簇必须提供什么」，不带实现。

    签名逐条来自拆分前的 `_HubQueue`（每个方法原样搬进某一个混入，所以本文件是那些签名的
    副本）——守卫 `tests/test_hub_queue_split.py` 把它与**真实现**逐参数对账，防止漂移。
    """

    def halt_of(self, course: str) -> bool: ...
    def all_halted(self) -> bool: ...
    def set_halt(self, halt: bool, course: str = "") -> bool: ...
    def add_course(self, name: str, mode: str = COURSE_MODE_ONLINE) -> bool: ...
    def _adopt_solo(self) -> None: ...
    def discover(self, force: bool = False) -> list[str]: ...
    def _serves_course(self, course: str) -> bool: ...
    def _course_dir_live(self, ent: Path, now: float) -> bool: ...
    @property
    def halt_workers(self) -> bool: ...
    @halt_workers.setter
    def halt_workers(self, v: bool) -> None: ...
    def auth_failure(self, ip: str) -> int: ...
    def auth_success(self, ip: str) -> None: ...
    def is_blocked(self, ip: str) -> bool: ...
    def blocked_remaining(self, ip: str) -> float: ...
    def _registry(self) -> dict[str, float]: ...
    def note_worker(self, worker_id: str) -> None: ...
    def active_worker_count(self) -> int: ...
    def courses(self) -> list[str]: ...
    def course_of(self, job_id: str) -> str | None: ...
    def mode_of(self, course: str) -> str: ...
    def offline_courses(self) -> list[str]: ...
    def set_mode(self, course: str, mode: str) -> bool: ...
    def active_courses(self) -> int: ...
    def claim_next(
        self, worker_id: str = "", role: str = ROLE_ONLINE
    ) -> tuple[str, str, str] | None: ...
    def traj_root(self) -> Path | None: ...
    def course_dir(self, course: str) -> Path: ...
    def resume_sources(self, course: str) -> list[dict]: ...
    def merge_eval_rows(self, course: str, rows: object) -> tuple[int, int]: ...
    def resume_anchor(self, course: str) -> dict | None: ...
    def task_pack_path(self, course: str) -> Path: ...
    def offline_progress(self) -> dict[str, dict]: ...
    def queue_state(self) -> dict: ...
    def _job_dir(self, job_id: str) -> Path: ...
    def job_root_of(self, course: str) -> Path | None: ...
    def shared_code_zip(self, course: str = "") -> Path | None: ...
    def _announce_freeze(self, course: str, jid: str) -> None: ...
    def claimable_job_ids(self, course: str) -> list[str]: ...
    def claim(
        self,
        job_id: str,
        ttl: float = CLAIM_TTL_SEC,
        worker_id: str = "",
        avoid_stale_holder: bool = False,
        mode: str | None = None,
        expected_epoch: int | None = None,
        role: str = ROLE_ONLINE,
    ) -> str | None: ...
    def peek_jobs(
        self,
        *,
        worker_id: str = "",
        role: str = ROLE_ONLINE,
        n: int = PEEK_MAX,
    ) -> list[dict]: ...
    def _manifest_summary(self, job_id: str) -> dict: ...
    def claim_job(
        self,
        job_id: str,
        *,
        mode: str = CLAIM_MODE_EXCLUSIVE,
        worker_id: str = "",
        expected_epoch: int | None = None,
        role: str = ROLE_ONLINE,
    ) -> ClaimOutcome: ...
    def priority_view(
        self,
        *,
        worker_id: str = "",
        job_ids: list[str] | None = None,
    ) -> tuple[int, dict[str, str], dict[str, str]]: ...
    def start_job(self, job_id: str, worker_id: str = "") -> bool: ...
    def set_ready(self, job_id: str, worker_id: str = "") -> bool: ...
    def abandon(self, job_id: str, worker_id: str = "") -> bool: ...
    def epoch_of(self, job_id: str) -> int: ...
    def job_status(self, job_id: str) -> dict: ...
    def job_priority_of(self, job_id: str, *, exclude_worker: str = "") -> str: ...
    def reclaims(self, job_id: str) -> int: ...
    def frozen_info(self, job_id: str) -> dict | None: ...
    def consume_freeze_announcement(self, job_id: str) -> dict | None: ...
    def unfreeze(self, job_id: str) -> dict | None: ...
    def frozen_jobs(self) -> list[str]: ...
    def heartbeat(self, job_id: str, lease_token: str) -> bool: ...
    def release(self, job_id: str, lease_token: str) -> bool: ...
    def result_token_ok(self, job_id: str, lease_token: str) -> bool: ...
    def store_result(self, job_id: str, result: dict) -> bool: ...
    def store_job_failure(self, job_id: str, rec: dict) -> bool: ...
    def job_failure(self, job_id: str) -> dict | None: ...
    def get_result(self, job_id: str) -> dict | None: ...
    def mark_completed(self, job_id: str) -> None: ...
    def record_payload_sent(self, job_id: str, n: int) -> None: ...
    def record_result_recv(self, job_id: str, n: int) -> None: ...
    def record_push_wire(self, job_id: str, n: int, payload_bytes: int, upload_sec: float) -> None: ...
    def wire_stats(self, job_id: str) -> dict: ...
    def store_bc_epoch(self, job_id: str, body: dict) -> bool: ...
    def get_bc_resume(self, job_id: str) -> dict | None: ...
    def get_bc_metrics(self, job_id: str) -> list[dict]: ...
    def lease_expires_in(self, job_id: str) -> float | None: ...
    def last_heartbeat_ago(self, job_id: str) -> float | None: ...
    def append_ledger(self, job_id: str, event: dict) -> None: ...
    def locate_offline_course(self, body: dict, query_course: str = "") -> str | None: ...
    def store_offline_artifact(self, course: str, body: dict) -> dict: ...
    def store_offline_result(self, course: str, body: dict) -> dict: ...

    def ambiguous_jids(self) -> dict[str, list[str]]: ...
